name: Deploy RaynaUI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Build all packages
        run: pnpm build
      - name: Test registry build
        run: |
          echo "Testing registry build..."
          pnpm --filter=v4 registry:test
        continue-on-error: false
      - name: Build registry
        run: |
          echo "Building registry..."
          pnpm --filter=v4 registry:build
        continue-on-error: false
      - name: Build documentation
        run: pnpm docs:build